### ISSUE TITLE
Vai ter acesso ao micro servico ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [loiane/crud-angular-spring#146]
`const baseUrl = 'http://localhost:8080/api/tutorials';

@Injectable({
  providedIn: 'root',
})
export class TutorialService {
  constructor(private http: HttpClient) {}

  getAll(): Observable<Tutorial[]> {
    return this.http.get<Tutorial[]>(baseUrl);
  }`

**Comment by loiane** [comment]
Olá, poderia fornecer um pouco mais de contexto?
