### ISSUE TITLE
Getting id from wrong instance

### ISSUE THREAD

**Issue by datazuul** [loiane/crud-angular-spring#273]
https://github.com/loiane/crud-angular-spring/blob/cd40cb13bc4ad1f3f1360f5ea1b2d91dcf27f95c/crud-spring/src/main/java/com/loiane/course/dto/mapper/CourseMapper.java#L32

Shouldn't this be

`if (lessonDTO._id() > 0) {
      lesson.setId(lessonDTO._id());
}`

**Comment by loiane** [comment]
@datazuul thanks for pointing it out.
