### ISSUE TITLE
Dúvidas de versões de NodeJS e Angular Cli

### ISSUE THREAD

**Issue by tarcisioreis** [loiane/crud-angular-spring#5]
Tenho um projeto com Angular Cli na versão 1.4.5 e NodeJS esta na versão 10.15.3 e ao executar npm run start ocorre um erro solicitando atualização do NodeJS para versão superior a que tenho atualmente mas, tenho receio de atualizar pois, tenho um projeto de cliente em produção e ao atualizar o NodeJS para versão superior não vai fazer com meu Angular Cli 1.4.5 desse projeto pare de funcionar ?

Em anexo imagem do que tenho no note em Windows 8.1. 64 Bits e erro que ocorre. Aguardo uma ajuda para resolver o erro sem bagunçar o que já tenho.
![config](https://github.com/loiane/crud-angular-spring/assets/7525518/978f6317-e47c-46f8-b00f-657002f36187)
![erro](https://github.com/loiane/crud-angular-spring/assets/7525518/75e0f36f-c145-47f9-b351-ca0e548b98fe)

**Comment by loiane** [comment]
Oie, uso o NVM pra gerencial múltiplas versões no Node.js: https://www.freecodecamp.org/news/nvm-for-windows-how-to-download-and-install-node-version-manager-in-windows-10/
Assim você consegue configurar qual versão do Node você quer usar em casa projeto.
